name: Deploy to Google App Engine (GAE)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Node Project
        env:
          NODE_ENV: production
        run: yarn build

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy dispatch.yaml
        run: |
          if [ -f "dispatch.yaml" ]; then
            gcloud app deploy dispatch.yaml --quiet;
          fi

      - name: Deploy app.yaml
        run: |
          gcloud app deploy app.yaml --quiet
